### ISSUE TITLE
Madon spawnaus ei toimi jos mato on mennyt vasemmasta seinästä ulos

### ISSUE THREAD

**Issue by SamiKarhunen** [SamiKarhunen/VerkkosovellusR1#3]
Tätä ongelmaa ei ole saatu ratkaistua, mutta tätä tutkaillessa huomasin että index.html tiedoston body onloadin funktiokutsu startGame on turha, koska sellaista metodia ei game.js:ssa ole

**Comment by SamiKarhunen** [comment]
Madon spawnauksen voi korjata esim määrittelemällä lähtösuunta aina vaikkapa oikealle initSnake funktion sisällä eli vaikkapa lisäämällä game.js riville 93 seuraava pätkä: direction = 2;

**Comment by burec** [comment]
Ongelma ratkaistu
